aspnet/AspLabs

- .gitignore
- sharedfx/NuGet.config
- sharedfx/build.ps1
- sharedfx/samples/NuGet.config
- sharedfx/samples/Web/Startup.cs
- sharedfx/samples/Web/Web.csproj
- sharedfx/samples/build.ps1
- sharedfx/src/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App.csproj
- sharedfx/src/Microsoft.AspNetCore.App/build/netcoreapp2.0/Microsoft.AspNetCore.App.props
- sharedfx/src/Microsoft.AspNetCore.App/crossgen.targets
- sharedfx/src/Microsoft.AspNetCore.App/dependencies.props
This code creates a .NET Core shared framework that includes everything Microsoft.AspNetCore.All already has.
Sample csproj (today)
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
<TargetFramework>netcoreapp2.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.0.0-preview1" />
</ItemGroup>
</Project>
```
If we added the implicit import to Microsoft.NET.Sdk.Web:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
<TargetFramework>netcoreapp2.0</TargetFramework>
</PropertyGroup>
</Project>
```
Trimmed output:
Installed to dotnet folder:
cc @davidfowl @DamianEdwards
> Prototype of an ASP.NET Core shared framework

- pkg/.gitignore
- pkg/build.ps1
- pkg/src/Microsoft.AspNetCore.App.RefOnly/Microsoft.AspNetCore.App.RefOnly.csproj
- pkg/src/lzma/redist/Program.cs
- pkg/src/lzma/redist/redist.csproj
- pkg/src/lzma/refs/refs.csproj
Comparison:
See https://github.com/aspnet/Universe/issues/1124 for more details on the composition of the current NuGetFallbackFolder
* 1,010 MB once expanded on disk
* ~670 MB of xml docs
* 181 MB of binaries
* 113 MB once expanded on disk
* 49 MB of xml docs
* 41MB of binaries
*And it can still get smaller!* This prototype still bundles the implementation binaries in Microsoft.AspNetCore.App.RefOnly. We could strip these down to actual ref assemblies.
@DamianEdwards @Petermarcu @davidfowl @weshaggard
> Produce an LZMA with the refonly package

- src/dotnet-monitor/Directory.Build.props
- src/dotnet-monitor/dotnet-monitor.sln
- src/dotnet-monitor/samples/SampleWebApp/Pages/Error.cshtml.cs
- src/dotnet-monitor/src/Common/ConsoleCancellation.cs
- src/dotnet-monitor/src/dotnet-dump/Dumper.Linux.cs
- src/dotnet-monitor/src/dotnet-dump/Dumper.Windows.cs
- src/dotnet-monitor/src/dotnet-dump/Dumper.cs
- src/dotnet-monitor/src/dotnet-dump/Program.cs
- src/dotnet-monitor/src/dotnet-dump/dotnet-dump.csproj
- src/dotnet-monitor/src/dotnet-trace/CollectCommand.cs
- src/dotnet-monitor/src/dotnet-trace/SourcesCommand.cs
Early prototype of `dotnet-dump`. Supports Windows only and just captures a dump of all memory.
Based on anurse/add-dotnet-monitor
> dotnet-dump for windows/linux, full dumps only

- src/dotnet-monitor/dotnet-monitor.sln
- src/dotnet-monitor/samples/SampleMonitoredApp/Program.cs
- src/dotnet-monitor/samples/SampleWebApp/Program.cs
- src/dotnet-monitor/src/Common/ConsoleCancellation.cs
- src/dotnet-monitor/src/dotnet-collect/EventPipeConfiguration.cs
- src/dotnet-monitor/src/dotnet-collect/EventSpec.cs
- src/dotnet-monitor/src/dotnet-collect/Program.cs
- src/dotnet-monitor/src/dotnet-collect/dotnet-collect.csproj
```
Collects Event Traces from .NET processes
Usage: dotnet-collect [options]
Options:
-c|--config-path <CONFIG_PATH>  The path of the EventPipe config file to write, must be named [AppName].eventpipeconfig and be in the base directory for a managed app.
-p|--process-id <PROCESS_ID>    Filter to only the process with the specified process ID.
-o|--output <OUTPUT_DIRECTORY>  The directory to write the trace to. Defaults to the current working directory.
--buffer <BUFFER_SIZE_IN_MB>    The size of the in-memory circular buffer in megabytes.
--provider <PROVIDER_SPEC>      An EventPipe provider to enable. A string in the form '<provider name>:<keywords>:<level>'. Can be specified multiple times to enable multiple providers.
-?|-h|--help                    Show help information
```
The …
> add dotnet-collect command that uses EventPipe

- src/dotnet-monitor/README.md
- src/dotnet-monitor/src/dotnet-analyze/AnalysisSession.cs
- src/dotnet-monitor/src/dotnet-analyze/CommandProcessor.cs
- src/dotnet-monitor/src/dotnet-analyze/Commands/DumpHeapCommand.cs
- src/dotnet-monitor/src/dotnet-analyze/Commands/DumpStackCommand.cs
- src/dotnet-monitor/src/dotnet-analyze/Commands/HelpCommand.cs
- src/dotnet-monitor/src/dotnet-analyze/Commands/IAnalysisCommand.cs
- src/dotnet-monitor/src/dotnet-analyze/Commands/ThreadsCommand.cs
- src/dotnet-monitor/src/dotnet-analyze/Program.cs
- src/dotnet-monitor/src/dotnet-analyze/TypeHeapStats.cs
- src/dotnet-monitor/src/dotnet-analyze/Utils.cs
An SOS-like "REPL" for exploring .NET memory dumps (based on [CLRMD](https://github.com/Microsoft/clrmd)).
```
Inspect a crash dump using interactive commands
Usage: dotnet-analyze [arguments] [options]
Arguments:
<DUMP>        The path to the dump file to analyze.
Options:
-?|-h|--help  Show help information
```
When you launch this command, a REPL prompt is provided:
```
Loading crash dump C:\Users\anurse\Desktop\dotnet-18956-20181012-153829-088.dmp...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the analysis session.
>
```
The following commands are available:
* `quit` (alias `exit`) - Exit the tool
* `help` - List commands and help information (not yet implemented ;))
* …
> dotnet-analyze - A CLRMD-based SOS-like REPL tool

- src/DotNetDiagnostics/src/Common/CommandLineException.cs
- src/DotNetDiagnostics/src/dotnet-collect/CollectionConfiguration.cs
- src/DotNetDiagnostics/src/dotnet-collect/CollectionProfile.cs
- src/DotNetDiagnostics/src/dotnet-collect/EventSpec.cs
- src/DotNetDiagnostics/src/dotnet-collect/KnownData.cs
- src/DotNetDiagnostics/src/dotnet-collect/Program.cs
- src/DotNetDiagnostics/src/dotnet-collect/dotnet-collect.csproj
Adds support for some predefined named profiles of useful events. Also `dotnet-collect` now has a "default" profile that enables useful .NET events even if no arguments are specified.
> Add profiles to dotnet-collect

- src/DotNetDiagnostics/src/dotnet-dump/Dumper.Windows.cs
Decorate the MINIDUMP_TYPE enum with the Flags attribute
Set the values of the MINIDUMP_TYPE enum to those found in minidumpapiset.h file from the Windows 10 SDK
> Set the MINIDUMP_TYPE enum values correctly

- src/HttpRepl/Microsoft.Repl/Input/InputManager.cs
> Turn off input canonicalization (icanon) to avoid the password cursor showing up on mac

- eng/Versions.props
- src/HttpRepl/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj
Verified that this works correctly by setting $ci to true and $OfficialBuildId to valid build number. It created the repl with right package version and other packages were still in alpha.
> Fixing the PreReleaseVersionLabel  condition

- src/HttpRepl/Microsoft.HttpRepl/Commands/HelpCommand.cs
- src/HttpRepl/Microsoft.Repl/ConsoleHandling/ConsoleManager.cs
Fixes the performance of the help command (6s to immediate on my machine); the same treatment can be applied to any other commands, and/or the ConsoleManager could be given a buffer and a Flush that would just flush it all out when called.
Also removed several unnecessary Console.CursorLeft/Top calls entirely from ConsoleManager.
cc: @bradygaster, @mlorbetske, @karelz, @wtgodbe
https://github.com/aspnet/AspLabs/issues/68#issuecomment-461591416
> Reduce ConsoleManager.Caret usage in help command

- Directory.Build.props
- eng/Versions.props
Prepares repo for change https://github.com/dotnet/arcade/pull/2003 by setting `Copyright` and `PackageLicenseExpression` properties. These values will be required to be set by each repository once https://github.com/dotnet/arcade/pull/2003 is merged.
In order to not break the current builds this change sets the properties conditionally. This condition can be removed once all repos switch to Arcade that has https://github.com/dotnet/arcade/pull/2003.
@markwilkie
> Set copyright and package license

- src/Proxy/src/ProxyAdvancedExtensions.cs
Reverts https://github.com/aspnet/AspLabs/pull/290 to fix the build.
It looks like IAsyncDisposable isn't available in netstandard2.0.
> Fix the build by removing async using

- src/ProxyProtocol/Client.Sample/Client.Sample.csproj
- src/ProxyProtocol/Client.Sample/Program.cs
- src/ProxyProtocol/ProxyProtocol.Sample/Program.cs
- src/ProxyProtocol/ProxyProtocol.Sample/ProxyProtocol.Sample.csproj
- src/ProxyProtocol/ProxyProtocol.Sample/ProxyProtocol.cs
- src/ProxyProtocol/ProxyProtocol.Sample/ProxyProtocolFeature.cs
- src/ProxyProtocol/ProxyProtocol.Sample/Startup.cs
- src/ProxyProtocol/ProxyProtocol.Sample/appsettings.Development.json
- src/ProxyProtocol/ProxyProtocol.Sample/appsettings.json
- src/ProxyProtocol/ProxyProtocol.sln
This is a sample for parsing the Proxy Protocol as a Kestrel connection middleware. The protocol allows level 4 proxies to forward information as a connection preface. The preface needs to be removed before HTTP parsing can happen.
We're publishing this to labs because multiple parties have expressed interest in it. We know it's not exhaustive, it (e.g. it only handles IPv4 addresses), but it's a good starting point for interested parties.
See https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt Section 2.2
Azure private link is one such proxy that sends this data:
https://docs.microsoft.com/en-us/azure/private-link/private-link-service-overview#properties (EnableProxyProtocol)
Ngnix has a first class implementation of this spec (inbound). …
> Add a ProxyProtocol sample

- src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs
- src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/UnaryServerCallHandlerTests.cs
Hi @JamesNK 
This PR includes two changes to gRPC Http API:
* For incorrect content-type, which is currently anything but `application/json`, it will return a 400 http error code, rather than 500.
* For malformed request body payloads, whether it's a malformed json or it doesn't conform to the request type, it will return 400 with the appropriate error message.
> Properly handle malformed request body and content type

- src/GrpcHttpApi/dependencies.props
- src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.Swagger/Internal/GrpcDataContractResolver.cs
Build GrpcHttpApi swagger support against latest NuGet to react to breaking change. Also using stop obsolete ForPrimative overload.
> Update GrpcHttpApi swagger version

- src/ApiTemplate/templates/ApiTemplate/Properties/OpenApi.cs
- Fix issue with RoutePrefix and ordering by using rewriter to map the desired paths to the default Swashbuckle paths
- Configure Swagger UI with the desired document path (/openapi.json) so the UI shows a link to that path
> Fix Swashbuckle registration in 'api' template

- src/BlazorCustomElements/src/Microsoft.AspNetCore.Components.CustomElements/js/WebpackBuild.targets
The published artifact wasn't including the `.js` file. Hopefully this change to the build setup will fix that.
> Update custom elements package build for SWA compatibility

- src/RateLimiting/src/ConcurrencyLimiter.cs
- src/RateLimiting/src/RateLimiter.cs
- src/RateLimiting/src/System.Threading.RateLimiting.csproj
- src/RateLimiting/src/TokenBucketRateLimiter.cs
- src/RateLimiting/src/TokenBucketRateLimiterOptions.cs
- src/RateLimiting/test/BaseRateLimiterTests.cs
- src/RateLimiting/test/ConcurrencyLimiterTests.cs
- src/RateLimiting/test/TokenBucketRateLimiterTests.cs
Depends on https://github.com/aspnet/AspLabs/pull/387 so there aren't two PRs adding the test infra/csproj properties.
> TokenBucketRateLimiter implementation

- src/SystemWebAdapters/src/Adapters/ISystemWebAdapterBuilder.cs
- src/SystemWebAdapters/src/Adapters/SystemWebAdaptersExtensions.cs
This follows the pattern of IMvcBuilder so that additional System.Web adapter services (such as session) can be chained onto it.
> Add ISystemWebAdapterBuilder to chain additional services

- src/SystemWebAdapters/samples/MvcApp/App_Start/RouteConfig.cs
- src/SystemWebAdapters/samples/MvcApp/Global.asax.cs
- src/SystemWebAdapters/samples/MvcApp/Web.config
- src/SystemWebAdapters/samples/MvcCoreApp/Program.cs
- src/SystemWebAdapters/src/Adapters/SessionState/RemoteAppSessionStateManager.cs
- src/SystemWebAdapters/src/Adapters/SessionState/RemoteAppSessionStateOptions.cs
- src/SystemWebAdapters/src/Adapters/SessionState/SessionSerializer.cs
- src/SystemWebAdapters/src/Content/Web.config.install.xdt
- src/SystemWebAdapters/src/Content/Web.config.uninstall.xdt
- src/SystemWebAdapters/src/Framework/RemoteAppSessionStateHandler.cs
- src/SystemWebAdapters/src/Framework/SystemWebAdapterExtensions.cs
- src/SystemWebAdapters/src/Framework/SystemWebAdapterModule.cs
This replaces the HttpHandler with a module so that we can have a central point to hook into various aspects of the framework app to support the adapters.
The remote session handler is now managed by the module so a user just needs to configure it and it will run rather than needing to configure it in web.config.
> Use module instead of handler

- src/SystemWebAdapters/src/Adapters/ISessionState.cs
- src/SystemWebAdapters/src/Adapters/SessionState/RemoteAppSessionStateManager.cs
- src/SystemWebAdapters/src/Adapters/SessionState/SessionSerializer.cs
- src/SystemWebAdapters/src/Caching/Cache.cs
- src/SystemWebAdapters/src/HttpContext.cs
- src/SystemWebAdapters/src/HttpCookie.cs
- src/SystemWebAdapters/src/HttpResponse.cs
- src/SystemWebAdapters/src/HttpResponseBase.cs
- src/SystemWebAdapters/src/HttpResponseWrapper.cs
- src/SystemWebAdapters/src/Ref.Standard.cs
- src/SystemWebAdapters/src/SessionState/HttpSessionState.cs
- src/SystemWebAdapters/src/SessionState/HttpSessionStateBase.cs
- src/SystemWebAdapters/src/SessionState/HttpSessionStateWrapper.cs
- src/SystemWebAdapters/src/System.Web.Adapters.csproj
- src/SystemWebAdapters/test/Adapters/SessionState/SessionStateSerialization.cs
- src/SystemWebAdapters/test/HttpContextTests.cs
- src/SystemWebAdapters/test/HttpResponseTests.cs
This change enables the SDK package validation to ensure we have the correct method signatures on the various builds. This will help catch regressions to APIs that are supposed to unify with .NET Framework. As part of this, a number of issues were flagged which are fixed with this change as well.
> Enable package validation

- src/SystemWebAdapters/samples/MvcApp/Global.asax.cs
- src/SystemWebAdapters/samples/MvcApp/Views/Home/Contact.cshtml
- src/SystemWebAdapters/samples/MvcApp/Views/Shared/_Layout.cshtml
- src/SystemWebAdapters/samples/MvcCoreApp/Program.cs
- src/SystemWebAdapters/samples/MvcCoreApp/Views/Shared/_Layout.cshtml
- src/SystemWebAdapters/src/Adapters/ISystemWebAdapterBuilder.Framework.cs
- src/SystemWebAdapters/src/Adapters/Modules/ProxyHeaderModule.Framework.cs
- src/SystemWebAdapters/src/Adapters/Modules/ProxyOptions.Framework.cs
- src/SystemWebAdapters/src/Adapters/Modules/RemoteSessionModule.Framework.cs
- src/SystemWebAdapters/src/Adapters/SystemWebAdapterModule.Framework.cs
- src/SystemWebAdapters/src/Adapters/SystemWebAdaptersExtensions.Framework.cs
- src/SystemWebAdapters/src/Content/Web.config.install.xdt
This change adds a module for the framework app that will handle proxy values. As part of this change, the SystemWebAdapter module will load any registered modules so that we can keep them specific to the feature they enable.
> Add proxy header support for adapters

- src/SystemWebAdapters/src/Adapters/ISessionState.cs
- src/SystemWebAdapters/src/Adapters/SessionAttribute.cs
- src/SystemWebAdapters/src/Adapters/SessionBehavior.cs
- src/SystemWebAdapters/src/Adapters/SessionMiddleware.cs
- src/SystemWebAdapters/src/Adapters/SessionState/DelegatingSessionState.cs
- src/SystemWebAdapters/src/Adapters/SessionState/RemoteAppSessionStateManager.cs
- src/SystemWebAdapters/src/Adapters/SessionState/SessionSerializer.cs
- src/SystemWebAdapters/src/ExcludedApis.txt
- src/SystemWebAdapters/src/Ref.Standard.cs
- src/SystemWebAdapters/src/SessionState/HttpSessionState.cs
- src/SystemWebAdapters/src/TypeForwards.Framework.cs
- src/SystemWebAdapters/test/Adapters/SessionState/SessionStateSerialization.cs
This adds an enum that allows for setting behavior for session to be none, eager loading (i.e. async in middleware), and on-demand that will only be when it is used.
> Add SessionBehavior to enable loading session on demand

- src/SystemWebAdapters/src/Microsoft.AspNetCore.SystemWebAdapters/HttpResponse.cs
https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.addheader?view=netframework-4.8
"[AddHeader](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.addheader?view=netframework-4.8) is the same as [AppendHeader](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.appendheader?view=netframework-4.8) and is provided only for compatibility with earlier versions of ASP. With ASP.NET, use [AppendHeader](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.appendheader?view=netframework-4.8)."
As opposed to AspNetCore Headers.Add which uses the Dictionary behavior that will throw if there are duplicate header names.
> Change AddHeader to Append

- src/GrpcHttpApi/README.md
Added section: Enable Swagger/OpenAPI support (authored originally by JamesNK).
Added links to packages that were referred to.
**Please note** 
I changed the first line from:
"gRPC HTTP API is an extension"
to:
"gRPC HTTP API is an experimental extension"
It was to clarify this project's status, but I want to make sure that was OK.
> Update README.md and add Enable Swagger - OpenAPI

- src/BlazorCustomElements/src/Microsoft.AspNetCore.Components.CustomElements/js/WebpackBuild.targets
- src/ClientAssets/Microsoft.AspNetCore.ClientAssets/build/netstandard2.0/Microsoft.AspNetCore.ClientAssets.targets
- avoid grabbing new `npm` packages w/o explicit (manual) action
> Use `npm ci` everywhere

- src/ClientAssets/Microsoft.AspNetCore.ClientAssets/build/netstandard2.0/Microsoft.AspNetCore.ClientAssets.targets
While the effort continues to productionize Microsoft.AspNetCore.ClientAssets, there needs to be an updated check to make sure that customers upgrading to .Net 7 don't break.
CC @mkArtakMSFT 
Fixes dotnet/aspnetcore#45849
> Add .Net 7 Check to ClientAssets

- src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/Paginator.razor
As per the [HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type), if a button's `type` is not explicitly specified, then it defaults to a `submit` type button.  This causes issues if the default QuickGrid Paginator is placed inside of an EditForm, as clicking any nav button triggers the EditContext's validation.
> explicitly identifying button type in paginator

- src/ClientAssets/samples/BlazorWasmAppWithJsAssets/assets/.npmrc
- src/ClientAssets/samples/BlazorWasmAppWithJsAssets/assets/package-lock.json
- src/ClientAssets/samples/SampleRazorClassLibraryWithJsAssets/assets/.npmrc
- src/ClientAssets/samples/SampleRazorClassLibraryWithJsAssets/assets/package-lock.json
- bump all resolved dependencies to latest compatible versions
- re-resolve everything but don't change any package.json files
- bump `json5`, `loader-utils`, and `minimatch` in particular
- all the subject of recent Dependabot PRs
- also add `always-auth=true` to .npmrc files
- required to ingest packages into `dotnet-public-npm`
Note: Unable to use just one .npmrc file here
- appears `yarn` looks up the tree by default but `npm` does not
> Recreate package-lock.json files

- Directory.Build.props
- src/AspNetCoreWebAPI/src/System.Web.Http.AspNetCore/System.Web.Http.AspNetCore.csproj
- src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.IntegrationTests/Microsoft.AspNetCore.Grpc.HttpApi.IntegrationTests.csproj
Address https://dev.azure.com/dnceng/internal/_componentGovernance/aspnet-AspLabs/alert/4810315?typeId=6333718 per https://github.com/dotnet/aspnetcore-internal/issues/4372#issuecomment-1720398783
> Upgrade System.Net.Http from 4.1.0 to 4.3.4 to fix the vulnerability (CVE-2022-34716)
