aspnet/AspLabs

src/HttpRepl/Microsoft.HttpRepl/OpenApi/PointerUtil.cs

Write the resolved token into arrays when resolving their children
Fixes #69 
Fixes #70

Add cycle detection for JSON pointer resolution

---

src/Proxy/README.md

Add link to ProxyKit as suggested by @Eilon at https://github.com/aspnet/AspLabs/issues/61#issuecomment-451210039

Add related projects section and link to proxykit

---

src/HttpRepl/Microsoft.HttpRepl.Tests/Microsoft.HttpRepl.Tests.csproj
src/HttpRepl/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj
src/HttpRepl/Microsoft.Repl.Tests/Microsoft.Repl.Tests.csproj
src/HttpRepl/Microsoft.Repl/Microsoft.Repl.csproj

Revert "Move projects to target netcoreapp3.0"

---

azure-pipelines.yml

- aspnet/AspNetCore#8862, aspnet/AspNetCore-Internal#2033
- convert YAML to use Arcade jobs.yml and job schema
- see https://github.com/dotnet/arcade/blob/master/Documentation/AzureDevOps/PhaseToJobSchemaChange.md
nits:
- remove unnecessary `contains(variables['Build.DefinitionName'], '...')` expressions
- use current (mcr.microsoft.com) location for Docker image
- reorder parameters for consistency

Do not specify `name` of the default (hosted) pools and move to BYOC queues on Windows

---

azure-pipelines.yml

- aspnet/AspNetCore-Internal#2124
- option was disabled prior to 49669c19ac

Do not publish to blob feed

---

azure-pipelines.yml

- aspnet/AspNetCore-Internal#2130

Disable publish to the BAR

---

azure-pipelines.yml

- aspnet/AspNetCore-Internal#2231
- use internal pools for all internal builds

Support internal pull requests

---

global.json
src/DotNetDiagnostics/samples/SampleWebApp/SampleWebApp.csproj
src/DotNetDiagnostics/samples/SampleWebApp/Startup.cs
src/Proxy/sample/Microsoft.AspNetCore.Proxy.Samples.csproj
src/WebHooks/samples/Directory.Build.props

@anurse any reason not to do this?

Move to 3.0 Preview 6 SDK

---

eng/Build.props
src/ProtectedBrowserStorage/sample/ProtectedBrowserStorageSample/ProtectedBrowserStorageSample.csproj
src/ProtectedBrowserStorage/src/ProtectedBrowserStorage.cs

Includes `ProtectedBrowserStorage.sln` in the set of solutions built in CI.

Build ProtectedBrowserStorage

---

eng/Build.props
src/GrpcHttpApi/GrpcHttpApi.sln
src/GrpcHttpApi/sample/Sample.sln
src/GrpcHttpApi/sample/Server/Server.csproj
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiProviderSeviceBinder.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/Microsoft.AspNetCore.Grpc.HttpApi.csproj
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/Proto/httpapi.proto

TODO: Change tests to use xunit

Build gRPC HTTP API package

---

src/GrpcHttpApi/sample/Server/Services/GreeterService.cs
src/GrpcHttpApi/sample/Server/wwwroot/index.html
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/RequestEncoding.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/ResponseEncoding.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs

Improve reading of request and response using blocking Google.Protobuf serializer. Matches formatters in MVC

Improve request reading and response writing

---

azure-pipelines.yml
src/ComponentsElectron/src/Microsoft.AspNetCore.Components.Electron.JS/yarn.lock

- dotnet/aspnetcore-internal#3540

Update hosted (AzDO) and BYOC (dnceng) agents used in our builds

---

src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/Internal/Protos/errors.proto
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/Microsoft.AspNetCore.Grpc.HttpApi.csproj
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/Microsoft.AspNetCore.Grpc.HttpApi.Tests.csproj
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/UnaryServerCallHandlerTests.cs

Fixes https://github.com/aspnet/AspLabs/issues/263

Handle exceptions thrown from gRPC methods

---

src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiProviderSeviceBinder.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/Proto/httpapi.proto
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/UnaryServerCallHandlerTests.cs

Fixes https://github.com/grpc/grpc-dotnet/issues/1213

Write default values in response JSON

---

src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/GrpcHttpApiOptions.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/GrpcHttpApiServiceExtensions.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiProviderSeviceBinder.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/HttpApiServiceMethodProvider.cs
src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/GrpcHttpApiServiceExtensionsTests.cs
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/Proto/httpapi.proto
src/GrpcHttpApi/test/Microsoft.AspNetCore.Grpc.HttpApi.Tests/UnaryServerCallHandlerTests.cs

Fixes https://github.com/grpc/grpc-dotnet/issues/1222

Add options to customize JSON serialization

---

azure-pipelines.yml

Use Ubuntu 18.04 build agents

---

eng/Build.props

Actually build the new template package

---

azure-pipelines.yml
eng/common/templates/post-build/channels/generic-internal-channel.yml
eng/common/templates/post-build/channels/generic-public-channel.yml

FYI @DamianEdwards. I'll verify this actually fixes the issue  on an internal build before merging.

Try fix publish step

---

azure-pipelines.yml
eng/Publish.props
eng/common/templates/post-build/channels/generic-internal-channel.yml
eng/common/templates/post-build/channels/generic-public-channel.yml

This was tested on the internal repo and it seems to be working.

Use publishing v3

---

azure-pipelines.yml

Part of https://github.com/dotnet/aspnetcore-internal/issues/3950

Move off of expiring machine pools

---

src/SystemWebAdapters/src/Constants.cs
src/SystemWebAdapters/src/HttpServerUtility.cs
src/SystemWebAdapters/src/HttpServerUtilityBase.cs
src/SystemWebAdapters/src/HttpServerUtilityWrapper.cs
src/SystemWebAdapters/src/Ref.Standard.cs
src/SystemWebAdapters/src/TypeForwards.Framework.cs
src/SystemWebAdapters/test/HttpServerUtilityTests.cs

This implements HttpServerUtility except MapPath which ends up bringing in a number of other things. This will be done in a separate PR.

Implement HttpServerUtility

---

src/QuickGrid/samples/QuickGridSamples.Core/Pages/InMemory.razor.css
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Infrastructure/ColumnsCollectedNotifier.cs
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Infrastructure/InternalGridContext.cs
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/PaginationState.cs
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/Paginator.razor.cs
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/Paginator.razor.css
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.cs
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.css
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js

Fixes most of https://github.com/dotnet/aspnetcore/issues/42338

Quickgrid fixes

---

src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/Paginator.razor
src/QuickGrid/src/Microsoft.AspNetCore.Components.QuickGrid/Pagination/Paginator.razor.css

It was using an SVG 2 feature not supported on all devices. Now it only uses SVG 1.

Fix pagination style

---

src/OpenApi/CodeGenerator/CodeGenerator.csproj
src/OpenApi/CodeGenerator/Program.cs
src/OpenApi/OpenApi.sln

Adds the starter files for the OpenAPI project.

Create Code Generator project

---

azure-pipelines.yml

- remove Ubuntu 18.04 on Ubuntu 18.04 Docker use
- use consolidated Windows build images

Update CI images

---

azure-pipelines-public.yml
azure-pipelines.yml

Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2401966&view=results
Part of https://github.com/dotnet/aspnetcore-internal/issues/4468

Convert to 1ES templates

---

src/GrpcHttpApi/sample/Server/Startup.cs
src/GrpcHttpApi/test/testassets/Sandbox/Startup.cs

Follow recommended guidance around Swagger UI only in development environments.

Only enable Swagger UI under development

---

azure-pipelines-public.yml
azure-pipelines.yml

Switch to macos-12

---

src/OpenApiXmlCommentGenerator/gen/Microsoft.AspNetCore.OpenApi.SourceGenerators.csproj

Fixes https://github.com/dotnet/dnceng/issues/4802. Must be merge-committed

Merge commits from internal
